# Generated by Django 5.2.11 on 2026-02-21 18:56

import pessoa.helpers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoafisica',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[pessoa.helpers.validators.validate_cpf]),
        ),
    ]
