# Generated by Django 5.2.11 on 2026-02-22 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_alter_pessoafisica_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pessoa.pessoa')),
                ('razao_social', models.CharField(db_index=True, max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
            ],
        ),
    ]
