# Generated by Django 5.2.11 on 2026-02-22 20:08

import django.db.models.deletion
import pessoa.helpers.validators_pj
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_pessoajuridica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoajuridica',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True, validators=[pessoa.helpers.validators_pj.validate_cnpj]),
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('telefone_fixo', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='pessoa.pessoa')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
    ]
